version: '3'

networks:
    nginx-php80-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container1
        ports:
            - "81:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php80-service
            - mysql8-service
        networks:
            - nginx-php80-mysql8-node

    # php
    php80-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php80-container1
        ports:
            - "8000:8000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php80-mysql8-node

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container1
        ports:
            - "5432:5432"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always #always restart unless stopped manually
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        networks:
            - nginx-php80-mysql8-node

    # node
    node-service:
        image: nfqlt/node16
        container_name: node-container1
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php80-mysql8-node
